name: ModeratorTools
version: ${project.version}
main: com.github.ukraine1449.moderatortools.ModeratorTools
api-version: 1.16
authors: [ Ukraine1449 ]
description: A plugin that gives moderators tools to help them do their jobs.
website: plugins.world
commands:
  getFood:
    description: gets the food level of another player
    permission: modplugin.getFood
  getHealth:
    description: gets the health level of another player
    permission: modplugin.getHealth
  god:
    description: puts you or another player into godmode
    permission: modplugin.god
  vanish:
    description: makes you or another player invisible
    permission: modplugin.vanish
  openinv:
    description: opens the inventory of the target player
    permission: modplugin.openInv
  openec:
    description: opens the inventory of the target player
    permission: modplugin.openEC