name: GetArmor
version: 1.0
main: com.github.ukraine1449.getarmor.GetArmor
api-version: 1.16
authors: [ Ukraine1449 ]
description: gets the health and enchantments of a piece of armor
website: Plugins.world
commands:
  getarmor:
    description: gets armor and enchantments
    permission: getarmor.getarmor